//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentBoilerplate.Messages.Developer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssertFailures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssertFailures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentBoilerplate.Messages.Developer.AssertFailures", typeof(AssertFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a non-instance method but received an instance method.
        /// </summary>
        public static string InstanceMethodIsInvalidForLocation {
            get {
                return ResourceManager.GetString("InstanceMethodIsInvalidForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; is null and should not be.
        /// </summary>
        public static string InstanceShouldNotBeNull {
            get {
                return ResourceManager.GetString("InstanceShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type &apos;{0}&apos; should have been registered but was not.
        /// </summary>
        public static string NoExceptionHandlerForType {
            get {
                return ResourceManager.GetString("NoExceptionHandlerForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is not of expected type &apos;{1}&apos;.
        /// </summary>
        public static string ParameterIsNotExpectedType {
            get {
                return ResourceManager.GetString("ParameterIsNotExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned instance type &apos;{0}&apos; is not of expected type &apos;{1}&apos;.
        /// </summary>
        public static string ReturnedTypeIsNotExpectedType {
            get {
                return ResourceManager.GetString("ReturnedTypeIsNotExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a non-null instance implementing ITryCatchBlockProvider but found null.
        /// </summary>
        public static string TryCatchProviderNotFound {
            get {
                return ResourceManager.GetString("TryCatchProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validator type &apos;{0}&apos; is incompatible with property &apos;{1}&apos; with type &apos;{2}&apos;.
        /// </summary>
        public static string ValidatorIsNotApplicable {
            get {
                return ResourceManager.GetString("ValidatorIsNotApplicable", resourceCulture);
            }
        }
    }
}
