//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentBoilerplate.Messages.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentBoilerplate.Messages.User.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access was denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max value &apos;{0}&apos; cannot be less than the min value &apos;{1}&apos;.
        /// </summary>
        public static string MaxCannotBeLessThanMin {
            get {
                return ResourceManager.GetString("MaxCannotBeLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The min value &apos;{0}&apos; cannot be more than the max value &apos;{1}&apos;.
        /// </summary>
        public static string MinCannotBeGreaterThanMax {
            get {
                return ResourceManager.GetString("MinCannotBeGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; must not be null.
        /// </summary>
        public static string PropertyMustNotBeNull {
            get {
                return ResourceManager.GetString("PropertyMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; with length &apos;{1}&apos; must be at least &apos;{2}&apos; in length.
        /// </summary>
        public static string StringPropertyLengthMustBeAtLeast {
            get {
                return ResourceManager.GetString("StringPropertyLengthMustBeAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; with length &apos;{1}&apos; must not be more than &apos;{2}&apos; in length.
        /// </summary>
        public static string StringPropertyLengthMustBeNoMoreThan {
            get {
                return ResourceManager.GetString("StringPropertyLengthMustBeNoMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error: The property &apos;{0}&apos; was not included in memoization.
        /// </summary>
        public static string SYS_OverlookedPropertyMemoization {
            get {
                return ResourceManager.GetString("SYS_OverlookedPropertyMemoization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component &apos;{0}&apos; requires a license but the provided license was invalid.
        /// </summary>
        public static string UnlicensedComponent {
            get {
                return ResourceManager.GetString("UnlicensedComponent", resourceCulture);
            }
        }
    }
}
